CREATE SCHEMA EC1_CC1M;

USE EC1_CC1M;

CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORNEC_COD INT PRIMARY KEY,
FORNEC_NOME VARCHAR(45) NOT NULL,
FORNEC_RUA VARCHAR(45) NOT NULL,
FORNEC_NUMRUA INT,
FORNEC_BAIRRO VARCHAR(45) NOT NULL,
FORNEC_CIDADE VARCHAR(45) NOT NULL,
FORNEC_ESTADO VARCHAR(45) NOT NULL,
FORNEC_PAIS VARCHAR(30) NOT NULL,
FORNEC_CODPOSTAL VARCHAR(10) NOT NULL,
FORNEC_TELEFONE VARCHAR(15) NOT NULL,
FORNEC_CONTATO TEXT NOT NULL
);

alter table FORNECEDORES add CEO varchar(30);
alter table FORNECEDORES modify column CEO varchar(45);
alter table FORNECEDORES change column CEO NOME_CFO varchar(45);
alter table FORNECEDORES drop column NOME_CFO;


CREATE TABLE IF NOT EXISTS FILIAIS(
FILIAL_COD INT PRIMARY KEY,
FILIAL_NOME VARCHAR(45) NOT NULL,
FILIAL_RUA VARCHAR(100) NOT NULL,
FILIAL_NUMRUA INT,
FILIAL_BAIRRO VARCHAR(50) NOT NULL,
FILIAL_CIDADE VARCHAR(50) NOT NULL,
FILIAL_ESTADO VARCHAR(50) NOT NULL,
FILIAL_PAIS VARCHAR(50) NOT NULL,
FILIAL_CODPOSTAL VARCHAR(10) NOT NULL,
FILIAL_CAPACIDADE TEXT NOT NULL);

alter table FILIAIS add REPRESENTANTE varchar(45);
alter table FILIAIS modify column REPRESENTANTE varchar(60);
alter table FILIAIS change column REPRESENTANTE NOME_REPRESENTANTE varchar(60);
alter table FILIAIS drop column NOME_REPRESENTANTE;

CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY,
PROD_NOME VARCHAR(50) NOT NULL,
PROD_DESCRICAO TEXT NOT NULL,
PROD_ESPECTEC TEXT NOT NULL,
PROD_QUANT DECIMAL(10,3) NOT NULL,
PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
PROD_UNIDMEDIDA VARCHAR(10) NOT NULL,
PROD_ESTOQ_MIN DECIMAL(10,3) NOT NULL
);

alter table PRODUTOS add SAIDA DATE;
alter table PRODUTOS modify column SAIDA DATETIME;
alter table PRODUTOS change column SAIDA RECEBIMENTO DATETIME;
alter table PRODUTOS drop column RECEBIMENTO;

CREATE TABLE IF NOT EXISTS PEDIDOS(
PED_CODIGO INT PRIMARY KEY,
PED_DATA DATE NOT NULL,
PED_HORA TIME NOT NULL,
PED_PREVISAO DATE NOT NULL,
PED_STATUS ENUM('PENDENTE','CONCLUÍDO','EM ESPERA'),
PED_FORNECEDOR INT NOT NULL, 
CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PED_FORNECEDOR) 
REFERENCES FORNECEDORES(FORNEC_COD) 
);

alter table PEDIDOS add COMPRADOR VARCHAR(45);
alter table PEDIDOS modify column COMPRADOR VARCHAR(60);
alter table PEDIDOS change column COMPRADOR NOME_COMPRADOR VARCHAR(60);
alter table PEDIDOS drop column NOME_COMPRADOR;


CREATE TABLE IF NOT EXISTS RECEBIMENTOS(
RECEB_DATA DATE NOT NULL,
RECEB_HORA TIME NOT NULL,
RECEB_QUANT_PROD DECIMAL(10,3),
RECEB_CONDICAO TEXT NOT NULL,
RECEB_PEDIDOS INT PRIMARY KEY,
CONSTRAINT FK_PEDIDOS FOREIGN KEY(RECEB_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO));

alter table RECEBIMENTOS add ENTREGADOR VARCHAR(45);
alter table RECEBIMENTOS modify column ENTREGADOR VARCHAR(60);
alter table RECEBIMENTOS change column ENTREGADOR NOMECOMPLETO_ENTREGADOR VARCHAR(60);
alter table RECEBIMENTOS drop column NOMECOMPLETO_ENTREGADOR;


CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
PDPR_PEDIDOS_COD INT,
PDPR_PRODUTOS_COD INT,
PRIMARY KEY(PDPR_PEDIDOS_COD,PDPR_PRODUTOS_COD),
PDPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT PDPR_FK_PEDIDOS_COD FOREIGN KEY(PDPR_PEDIDOS_COD) REFERENCES PEDIDOS(PED_CODIGO),
CONSTRAINT PDPR_FK_PRODUTOS_COD FOREIGN KEY(PDPR_PRODUTOS_COD) REFERENCES PRODUTOS(PROD_COD)
);

alter table PEDIDOS_PRODUTOS add MATERIAIS VARCHAR(45);
alter table PEDIDOS_PRODUTOS modify column MATERIAIS TEXT;
alter table PEDIDOS_PRODUTOS change column MATERIAIS COMPONENTES TEXT;
alter table PEDIDOS_PRODUTOS drop column COMPONENTES;

CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS(
FLPR_FILIAL_COD INT,
FLPR_PRODUTOS_COD INT,
PRIMARY KEY(FLPR_FILIAL_COD,FLPR_PRODUTOS_COD),
FLPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT FLPR_FK_FILIAIS_COD FOREIGN KEY(FLPR_FILIAL_COD) REFERENCES FILIAIS(FILIAL_COD),
CONSTRAINT FLPR_FK_PRODUTOS_COD FOREIGN KEY(FLPR_PRODUTOS_COD) REFERENCES PRODUTOS(PROD_COD));

alter table FILIAIS_PRODUTOS add VENDEDOR VARCHAR(45);
alter table FILIAIS_PRODUTOS modify column VENDEDOR VARCHAR(60);
alter table FILIAIS_PRODUTOS change column VENDEDOR NOME_VENDEDOR VARCHAR(60);
alter table FILIAIS_PRODUTOS drop column NOME_VENDEDOR;

CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
FRPR_FORNECEDOR_COD INT,
FRPR_PRODUTOS_COD INT,
PRIMARY KEY(FRPR_FORNECEDOR_COD,FRPR_PRODUTOS_COD),
CONSTRAINT FRPR_FK_FORNECEDORES_COD FOREIGN KEY(FRPR_FORNECEDOR_COD)
REFERENCES FORNECEDORES(FORNEC_COD),
CONSTRAINT FRPR_FK_PRODUTOS_COD FOREIGN KEY(FRPR_PRODUTOS_COD) 
REFERENCES PRODUTOS(PROD_COD));

alter table FORNECEDORES_PRODUTOS add NOME_FORNECEDOR VARCHAR(45);
alter table FORNECEDORES_PRODUTOS modify column NOME_FORNECEDOR VARCHAR(60);
alter table FORNECEDORES_PRODUTOS change column NOME_FORNECEDOR FORNECEDOR VARCHAR(60);
alter table FORNECEDORES_PRODUTOS drop column FORNECEDOR;


create table if not exists teste(
id_teste int primary key not null
);

drop table teste;
